export default {
	criteria: [
		'1.3.1',
		'1.4.1',
		'1.4.4',
		'2.1.1',
		'2.1.2',
		'2.4.7',
		'2.5.3',
		'3.2.1',
		'3.2.2',
		'3.3.1',
		'3.3.2',
		'4.1.2'
	],
	requirements: {
		structure: [
			'`<input type="text">`',
			'`<CSDataTable>` - dropdown',
			'Clear button is `<CSButton>`'
		],
		attributes: [
			'`id` - needed to connect label with form element. If there is no id, autogenerated unique id is set',
			'`aria-expanded` - true when select is opened',
			'`aria-invalid` - true when there is an error',
			'`aria-required` - true when selecting an option is required',
			'`aria-multiselectable` - announces if multi selection is possible'
		],
		keyboardOperability: [
			'`<input>` OOTB focusable',
			'`<CSButton>` - focusable and supports clicks with `Enter` and `Space`'
		]
	}
};
