export default {
	criterionList: [
		'1.3.1',
		'1.4.1',
		'1.4.4',
		'2.1.1',
		'2.1.2',
		'2.4.7',
		'2.5.3',
		'3.2.1',
		'3.2.2',
		'3.3.1',
		'3.3.2',
		'4.1.2'
	],
	requirements: {
		structure: [
			'`<input type="radio">` - visually hidden',
			'`<span>` imitates radio with custom style',
			'`<input>` and `<span>` wrapped in `<label>` - allowing click on span to change input'
		],
		attributes: [
			'`aria-label` - description of radio group when label is hidden',
			'`aria-required` - true when selecting an option is required',
			'`aria-invalid` - true when there is an error',
			'`id` - needed to connect label with form element. If there is no id, autogenerated unique id is set',
			'`role="radio"` - implicit with input `<type="radio">`'
		],
		keyboardOperability: [
			'`<input type="radio">` OOTB focusable and supports `Space`'
		]
	}
};
